"""The 81 MOGREPS-G surface diagnostics in the study. Source: cycle inventory 2026-09-16 T0000Z."""

import os

# Inventory rows whose diagnostic does not end in `_levels.nc` (102 total - 21 level).
SURFACE_SLUGS: tuple[str, ...] = (
    "CAPE_mixed_layer_lowest_500m",
    "CAPE_most_unstable_below_500hPa",
    "CAPE_surface",
    "CIN_mixed_layer_lowest_500m",
    "CIN_most_unstable_below_500hPa",
    "CIN_surface",
    "boundary_layer_depth",
    "cloud_amount_below_1000ft_ASL",
    "cloud_amount_of_high_cloud",
    "cloud_amount_of_low_cloud",
    "cloud_amount_of_medium_cloud",
    "cloud_amount_of_total_cloud",
    "cloud_amount_of_total_convective_cloud",
    "fog_fraction_at_screen_level",
    "geopotential_height_at_freezing_level",
    "height_ASL_at_base_of_convective_inflow",
    "height_ASL_at_cloud_base_where_cloud_cover_2p5_oktas",
    "height_ASL_at_cloud_base_where_cloud_cover_4p5_oktas",
    "height_ASL_at_mixed_layer_CAPE_equilibrium_level",
    "height_ASL_at_most_unstable_CAPE_equilibrium_level",
    "height_ASL_at_most_unstable_CAPE_initiation_level",
    "height_ASL_at_top_of_convective_inflow",
    "height_ASL_at_wet_bulb_freezing_level",
    "height_of_orography",
    "landsea_mask",
    "latent_heat_flux_at_surface",
    "precipitation_accumulation-PT01H",
    "precipitation_accumulation-PT03H",
    "precipitation_rate",
    "pressure_at_convective_cloud_base",
    "pressure_at_convective_cloud_top",
    "pressure_at_mean_sea_level",
    "pressure_at_surface",
    "pressure_at_tropopause",
    "radiation_flux_in_longwave_downward_at_surface",
    "radiation_flux_in_longwave_outgoing_at_top_of_atmosphere",
    "radiation_flux_in_shortwave_diffuse_downward_at_surface",
    "radiation_flux_in_shortwave_direct_downward_at_surface",
    "radiation_flux_in_shortwave_net_at_surface",
    "radiation_flux_in_shortwave_total_downward_at_surface",
    "radiation_flux_in_uv_downward_at_surface",
    "radiation_flux_in_uv_upward_at_surface",
    "rainfall_accumulation-PT01H",
    "rainfall_accumulation-PT03H",
    "rainfall_accumulation_from_convection-PT01H",
    "rainfall_accumulation_from_convection-PT03H",
    "rainfall_rate",
    "rainfall_rate_from_convection",
    "rainfall_rate_from_convection_max-PT01H",
    "rainfall_rate_from_convection_max-PT03H",
    "rainfall_rate_max-PT01H",
    "rainfall_rate_max-PT03H",
    "relative_humidity_at_screen_level",
    "sensible_heat_flux_at_surface",
    "snow_depth_water_equivalent",
    "snowfall_accumulation-PT01H",
    "snowfall_accumulation-PT03H",
    "snowfall_accumulation_from_convection-PT01H",
    "snowfall_accumulation_from_convection-PT03H",
    "snowfall_rate",
    "snowfall_rate_from_convection",
    "snowfall_rate_from_convection_max-PT01H",
    "snowfall_rate_from_convection_max-PT03H",
    "snowfall_rate_max-PT01H",
    "snowfall_rate_max-PT03H",
    "specific_humidity_at_screen_level",
    "temperature_at_screen_level",
    "temperature_at_screen_level_max-PT01H",
    "temperature_at_screen_level_max-PT03H",
    "temperature_at_screen_level_min-PT01H",
    "temperature_at_screen_level_min-PT03H",
    "temperature_at_surface",
    "temperature_of_dew_point_at_screen_level",
    "visibility_at_screen_level",
    "wind_direction_at_10m",
    "wind_gust_at_10m",
    "wind_gust_at_10m_max-PT01H",
    "wind_gust_at_10m_max-PT03H",
    "wind_speed_at_10m",
    "wind_speed_at_10m_max-PT01H",
    "wind_speed_at_10m_max-PT03H",
)


def study_slugs() -> list[str]:
    """Override with WXTCO_SLUGS=a,b,c for small runs."""
    env = os.environ.get("WXTCO_SLUGS")
    if env:
        return [s.strip() for s in env.split(",") if s.strip()]
    return list(SURFACE_SLUGS)
