// Interactive charts for the MOGREPS-G storage TCO study.
// Dependency-free ES module. Defines four custom elements:
//   <wxtco-storage>  <wxtco-ingest>  <wxtco-queries>  <wxtco-tco>
// Data comes from ./wxtco-data.js (generated by scripts/export_web_data.py).
import DATA from "./wxtco-data.js";

const NS = "http://www.w3.org/2000/svg";
const METHODS = DATA.methods;
const BY_ID = Object.fromEntries(METHODS.map((m) => [m.id, m]));
const ORDER = METHODS.map((m) => m.id);
const P = DATA.prices;
const HOUR = 3600;
const DAYS = 30;

// Cost components of the TCO stack, in stack order (bottom to top).
const COMPONENTS = [
  { id: "storage", label: "Storage", color: "var(--wx-c1)" },
  { id: "etl", label: "Ingest", color: "var(--wx-c2)" },
  { id: "q1", label: "Q1 point series", color: "var(--wx-c3)" },
  { id: "q2", label: "Q2 regional stats", color: "var(--wx-c4)" },
  { id: "q3", label: "Q3 dataloader", color: "var(--wx-c5)" },
];

// ---------- styles (injected once) ----------
const CSS = `
.wx { --wx-surface:#ffffff; --wx-page:#F5F5F5; --wx-ink:#201F2C; --wx-ink-2:#4e4e4e; --wx-ink-3:#787878;
  --wx-rule:#e4e4e4; --wx-rule-2:#d1d1d1; --wx-grid:#ececec; --wx-accent:#6D0EDB; --wx-accent-soft:#A653FF;
  --wx-c1:#801fd2; --wx-c2:#b71a12; --wx-c3:#2091c2; --wx-c4:#c86b00; --wx-c5:#9f2e7f; --wx-copy:#8a8a8a;
  display:block; font-family: inherit; color: var(--wx-ink); font-size: 14px; line-height: 1.45; margin: 1.5em 0; }
.wx * { box-sizing: border-box; }
.wx-card { background: var(--wx-surface); border: 1px solid var(--wx-rule); border-radius: 12px; padding: 16px 16px 12px; position: relative; }
.wx-head { display: flex; flex-wrap: wrap; align-items: baseline; justify-content: space-between; gap: 6px 16px; margin-bottom: 10px; }
.wx-title { font-weight: 600; font-size: 15px; margin: 0; color: var(--wx-ink); }
.wx-sub { color: var(--wx-ink-3); font-size: 13px; margin: 0; }
.wx-controls { display: flex; flex-wrap: wrap; gap: 8px 18px; align-items: center; margin-bottom: 12px; }
.wx-group { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }
.wx-label { font-size: 11.5px; letter-spacing: .06em; text-transform: uppercase; color: var(--wx-ink-3); margin-right: 2px; }
.wx-chip { font: inherit; font-size: 13px; color: var(--wx-ink-2); background: var(--wx-page); border: 1px solid var(--wx-rule-2);
  border-radius: 999px; padding: 4px 11px; cursor: pointer; display: inline-flex; align-items: center; gap: 7px; line-height: 1.3; }
.wx-chip::before { content: ""; width: 8px; height: 8px; border-radius: 50%; border: 1.5px solid var(--wx-ink-3); }
.wx-chip[aria-pressed="true"] { color: var(--wx-ink); background: var(--wx-surface); border-color: var(--wx-accent); }
.wx-chip[aria-pressed="true"]::before { background: var(--wx-accent-soft); border-color: var(--wx-accent-soft); }
.wx-seg { display: inline-flex; border: 1px solid var(--wx-rule-2); border-radius: 8px; overflow: hidden; }
.wx-seg button { font: inherit; font-size: 13px; color: var(--wx-ink-2); background: var(--wx-surface); border: 0; padding: 5px 12px; cursor: pointer; }
.wx-seg button + button { border-left: 1px solid var(--wx-rule-2); }
.wx-seg button[aria-pressed="true"] { background: var(--wx-ink); color: #fff; }
.wx-act { font: inherit; font-size: 12.5px; color: var(--wx-accent); background: none; border: 0; padding: 4px 6px; cursor: pointer; text-decoration: underline; text-underline-offset: 3px; }
.wx-chip:focus-visible, .wx-seg button:focus-visible, .wx-act:focus-visible, .wx-hit:focus-visible { outline: 2px solid var(--wx-accent); outline-offset: 2px; }
.wx-legend { display: flex; flex-wrap: wrap; gap: 4px 16px; font-size: 13px; color: var(--wx-ink-2); margin: 4px 0 6px; }
.wx-legend span { display: inline-flex; align-items: center; gap: 7px; }
.wx-legend i { width: 10px; height: 10px; border-radius: 2px; display: inline-block; }
.wx-legend .wx-better { margin-left: auto; color: var(--wx-ink-3); }
.wx-plot { position: relative; overflow-x: auto; }
.wx svg { display: block; max-width: 100%; height: auto; overflow: visible; }
.wx svg[data-wide] { max-width: none; }
.wx svg text { font-family: inherit; font-size: 11.5px; fill: var(--wx-ink-3); }
.wx svg text.wx-cat { font-size: 12.5px; fill: var(--wx-ink); }
.wx svg text.wx-cat2 { font-size: 11px; fill: var(--wx-ink-3); }
.wx svg text.wx-val { font-size: 11.5px; fill: var(--wx-ink-2); }
.wx svg .wx-hit { fill: transparent; cursor: default; }
.wx svg .wx-hit:hover ~ .wx-bar, .wx svg g:hover .wx-bar { filter: brightness(1.08); }
.wx-tip { position: absolute; pointer-events: none; background: var(--wx-ink); color: #fff; font-size: 12.5px; line-height: 1.45;
  padding: 8px 10px; border-radius: 6px; max-width: 280px; z-index: 5; box-shadow: 0 2px 8px rgba(0,0,0,.15); }
.wx-tip b { font-weight: 600; }
.wx-tip .wx-row { display: flex; justify-content: space-between; gap: 14px; }
.wx-tip .wx-row i { width: 10px; height: 3px; border-radius: 2px; display: inline-block; margin-right: 6px; vertical-align: middle; }
.wx-tip .wx-muted { opacity: .7; }
.wx-foot { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 6px 16px; margin-top: 8px; font-size: 12.5px; color: var(--wx-ink-3); }
.wx-foot p { margin: 0; }
.wx-table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 10px; }
.wx-table th, .wx-table td { text-align: right; padding: 6px 10px; border-bottom: 1px solid var(--wx-rule); white-space: nowrap; font-variant-numeric: tabular-nums; }
.wx-table th:first-child, .wx-table td:first-child { text-align: left; }
.wx-table thead th { font-weight: 500; font-size: 11.5px; letter-spacing: .05em; text-transform: uppercase; color: var(--wx-ink-3); }
.wx-table-wrap { overflow-x: auto; }
.wx-small { display: grid; gap: 16px; }
.wx-small h4 { margin: 0 0 2px; font-size: 13.5px; font-weight: 600; color: var(--wx-ink); }
.wx-small h4 span { font-weight: 400; color: var(--wx-ink-3); margin-left: 8px; font-size: 12.5px; }
.wx-params { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px 20px; margin-bottom: 12px; }
.wx-param label { display: flex; justify-content: space-between; font-size: 13px; color: var(--wx-ink-2); margin-bottom: 4px; gap: 8px; }
.wx-param label output { font-variant-numeric: tabular-nums; color: var(--wx-ink); font-weight: 600; }
.wx-param input[type=range] { width: 100%; accent-color: var(--wx-accent); margin: 0; }
.wx-param small { display: block; color: var(--wx-ink-3); font-size: 11.5px; margin-top: 2px; }
.wx-empty { color: var(--wx-ink-3); padding: 24px 0; }
@media (max-width: 560px) { .wx-card { padding: 12px 12px 10px; } .wx-head { margin-bottom: 8px; } }
`;

let cssInjected = false;
function injectCss() {
  if (cssInjected || typeof document === "undefined") return;
  const s = document.createElement("style");
  s.textContent = CSS;
  document.head.appendChild(s);
  cssInjected = true;
}

// ---------- formatting ----------
const fmtInt = (v) => Math.round(v).toLocaleString("en-US");
function usd(v, { compact = false } = {}) {
  if (v == null) return "–";
  if (v === 0) return "$0";
  if (compact && v >= 10000) return "$" + (v / 1000).toFixed(v >= 100000 ? 0 : 1) + "k";
  if (v >= 100) return "$" + fmtInt(v);
  if (v >= 1) return "$" + v.toFixed(2);
  if (v >= 0.01) return "$" + v.toFixed(3);
  return "$" + v.toPrecision(2);
}
function secs(v) {
  if (v == null) return "–";
  if (v >= 100) return fmtInt(v) + " s";
  if (v >= 10) return v.toFixed(1) + " s";
  return v.toFixed(2) + " s";
}
function mins(v) {
  if (v == null) return "–";
  const m = v / 60;
  return (m >= 10 ? m.toFixed(0) : m.toFixed(1)) + " min";
}
function gb(v) {
  if (v == null) return "–";
  if (v >= 1000) return (v / 1000).toFixed(v >= 10000 ? 1 : 2) + " TB";
  if (v >= 100) return fmtInt(v) + " GB";
  return v.toFixed(1) + " GB";
}
function bytes(v) {
  if (v == null) return "–";
  if (v >= 1e9) return (v / 1e9).toFixed(v >= 1e10 ? 0 : 2) + " GB";
  if (v >= 1e6) return Math.round(v / 1e6) + " MB";
  return Math.round(v / 1e3) + " KB";
}
// Axis tick: as many decimals as the tick step needs, so a 2.5 step never rounds to 3.
function tick(v, unit, step = 1) {
  if (v === 0) return "0";
  const dec = Math.max(0, -Math.floor(Math.log10(step) + 1e-9));
  if (unit === "usd") return v >= 1000 ? "$" + +(v / 1000).toFixed(1) + "k" : "$" + v.toFixed(dec);
  if (v >= 1000) return +(v / 1000).toFixed(1) + "k";
  return v.toFixed(dec);
}
function niceStep(max, n = 4) {
  if (max <= 0) return 1;
  const raw = max / n;
  const mag = 10 ** Math.floor(Math.log10(raw));
  const f = raw / mag;
  return (f <= 1 ? 1 : f <= 2 ? 2 : f <= 2.5 ? 2.5 : f <= 5 ? 5 : 10) * mag;
}

// ---------- cost model (mirrors src/wxtco/tco.py) ----------
// One run of a query: instance time plus S3 requests (GET and HEAD at the GET tier, LIST at the PUT tier).
const computeUsd = (s) => (s == null ? 0 : (s / HOUR) * P.query_usd_per_hour);
function requestUsd(r) {
  if (!r) return 0;
  return ((r.get + r.head) * P.s3_get_per_1000 + r.list * P.s3_list_per_1000) / 1000;
}
const queryUsd = (q) => computeUsd(q.seconds) + requestUsd(q.requests);
function costs(m, w, includeCopy) {
  const storage = (m.storage_gb + (includeCopy ? DATA.netcdf_gb : 0)) * P.s3_gb_month;
  const etl = m.etl_seconds == null ? 0 : (m.etl_seconds / HOUR) * P.etl_usd_per_hour * w.etl_cycles * DAYS;
  const out = { storage, etl, compute: {}, requests: {} };
  for (const id of ["q1", "q2", "q3"]) {
    const q = m.queries[id];
    out.compute[id] = computeUsd(q.seconds) * w[id] * DAYS;
    out.requests[id] = requestUsd(q.requests) * w[id] * DAYS;
    out[id] = out.compute[id] + out.requests[id];
  }
  out.total = out.storage + out.etl + out.q1 + out.q2 + out.q3;
  return out;
}
const etlUsdPerCycle = (m) => (m.etl_seconds == null ? 0 : (m.etl_seconds / HOUR) * P.etl_usd_per_hour);

// ---------- DOM helpers ----------
function h(tag, attrs = {}, ...children) {
  const el = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {
    if (k === "class") el.className = v;
    else if (k.startsWith("on")) el.addEventListener(k.slice(2), v);
    else if (v != null) el.setAttribute(k, v);
  }
  for (const c of children.flat()) if (c != null) el.append(c);
  return el;
}
function svgEl(tag, attrs = {}, text) {
  const el = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) if (v != null) el.setAttribute(k, v);
  if (text != null) el.textContent = text;
  return el;
}
function storage(key, fallback) {
  try {
    const v = JSON.parse(localStorage.getItem(key));
    return v == null ? fallback : v;
  } catch {
    return fallback;
  }
}
function persist(key, v) {
  try {
    localStorage.setItem(key, JSON.stringify(v));
  } catch {
    /* private mode or blocked storage: selection is per-load only */
  }
}

// Segmented control. `options` is [{id, label}]; `onChange(id)`.
function segmented(options, value, onChange, ariaLabel) {
  const root = h("div", { class: "wx-seg", role: "group", "aria-label": ariaLabel });
  const update = (v) => root.querySelectorAll("button").forEach((b) => b.setAttribute("aria-pressed", b.dataset.id === v ? "true" : "false"));
  for (const o of options) {
    root.append(h("button", { type: "button", "data-id": o.id, "aria-pressed": String(o.id === value), onclick: () => { update(o.id); onChange(o.id); } }, o.label));
  }
  return root;
}

// Method chips. `sel` is a Set of ids; `onChange()` after each toggle.
function chips(ids, sel, onChange, presets = []) {
  const row = h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "Methods"));
  const buttons = ids.map((id) => {
    const b = h("button", { type: "button", class: "wx-chip", "aria-pressed": String(sel.has(id)) }, BY_ID[id].label);
    b.addEventListener("click", () => {
      sel.has(id) ? sel.delete(id) : sel.add(id);
      sync();
      onChange();
    });
    return [id, b];
  });
  const sync = () => buttons.forEach(([id, b]) => b.setAttribute("aria-pressed", String(sel.has(id))));
  row.append(...buttons.map(([, b]) => b));
  for (const p of presets) {
    row.append(h("button", { type: "button", class: "wx-act", onclick: () => { sel.clear(); p.ids.forEach((i) => sel.add(i)); sync(); onChange(); } }, p.label));
  }
  return row;
}

// Tooltip bound to a card. show(ev, html-builder) / hide().
function tooltip(card) {
  const tip = h("div", { class: "wx-tip", hidden: "" });
  card.append(tip);
  return {
    show(ev, build) {
      tip.replaceChildren();
      build(tip);
      tip.hidden = false;
      const b = card.getBoundingClientRect();
      const x = Math.max(8, Math.min(ev.clientX - b.left + 14, b.width - tip.offsetWidth - 8));
      const y = ev.clientY - b.top + 14;
      tip.style.left = x + "px";
      tip.style.top = y + "px";
    },
    showAt(el, build) {
      const r = el.getBoundingClientRect();
      this.show({ clientX: r.left + r.width / 2, clientY: r.top }, build);
    },
    hide() {
      tip.hidden = true;
    },
  };
}
const tipRow = (label, value, color) =>
  h("div", { class: "wx-row" }, h("span", {}, color ? h("i", { style: `background:${color}` }) : null, label), h("b", {}, value));

// ---------- column chart ----------
// series: [{label, color, values: {catId: number}}] stacked in order.
// cats: [{id, label, sub}]. unit: "usd" | "s" | "gb" | "min". fmt: value formatter for cap labels.
function columnChart({ cats, series, unit, fmt, width, onHover, onLeave, capLabel = true, heightPx = 260 }) {
  const T = 18, B = 46, L = 54, R = 10;
  const MIN_BAND = 72;
  const W = Math.max(width, 260, cats.length * MIN_BAND + L + R), H = heightPx;
  const svg = svgEl("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, role: "img" });
  if (W > width) svg.setAttribute("data-wide", "");
  const totals = cats.map((c) => series.reduce((a, s) => a + (s.values[c.id] || 0), 0));
  const vmax = Math.max(...totals, 0);
  const step = niceStep(vmax);
  const top = vmax > 0 ? Math.ceil(vmax / step + 1e-9) * step : 1;
  const ph = H - T - B;
  const y = (v) => T + ph - (v / top) * ph;
  for (let t = 0; t <= top + step / 2; t += step) {
    svg.append(svgEl("line", { x1: L, x2: W - R, y1: y(t), y2: y(t), stroke: t === 0 ? "var(--wx-rule-2)" : "var(--wx-grid)", "stroke-width": 1 }));
    svg.append(svgEl("text", { x: L - 8, y: y(t) + 4, "text-anchor": "end" }, tick(t, unit, step)));
  }
  const band = (W - L - R) / cats.length;
  const bw = Math.min(24, band * 0.6);
  const GAP = 2;
  const label = `${cats.map((c, i) => `${c.label} ${fmt(totals[i])}`).join(", ")}`;
  svg.setAttribute("aria-label", label);
  cats.forEach((c, i) => {
    const cx = L + band * i + band / 2;
    const g = svgEl("g", { tabindex: 0, class: "wx-hit", "aria-label": `${c.label}: ${fmt(totals[i])}` });
    g.append(svgEl("rect", { class: "wx-hit", x: cx - band / 2, y: T, width: band, height: H - T }));
    let acc = 0;
    const segs = series.filter((s) => (s.values[c.id] || 0) > 0);
    segs.forEach((s, k) => {
      const v = s.values[c.id];
      const y0 = y(acc + v), y1 = y(acc);
      const isTop = k === segs.length - 1;
      let hh = y1 - y0 - (k > 0 ? GAP : 0);
      if (hh < 1.5) hh = 1.5;
      const yy = y1 - hh;
      const x0 = cx - bw / 2;
      const r = isTop ? Math.min(4, bw / 2, hh) : 0;
      const d = `M${x0},${yy + hh} V${yy + r} Q${x0},${yy} ${x0 + r},${yy} H${x0 + bw - r} Q${x0 + bw},${yy} ${x0 + bw},${yy + r} V${yy + hh} Z`;
      g.append(svgEl("path", { class: "wx-bar", d, fill: s.color }));
      acc += v;
    });
    if (capLabel) {
      const txt = totals[i] === 0 && cats[i].zeroLabel ? cats[i].zeroLabel : fmt(totals[i]);
      g.append(svgEl("text", { x: cx, y: y(totals[i]) - 6, "text-anchor": "middle", class: "wx-val" }, txt));
    }
    g.append(svgEl("text", { x: cx, y: H - B + 17, "text-anchor": "middle", class: "wx-cat" }, c.label));
    if (c.sub) g.append(svgEl("text", { x: cx, y: H - B + 32, "text-anchor": "middle", class: "wx-cat2" }, c.sub));
    if (onHover) {
      g.addEventListener("pointermove", (ev) => onHover(ev, c, totals[i]));
      g.addEventListener("pointerleave", onLeave);
      g.addEventListener("focus", () => onHover(null, c, totals[i], g));
      g.addEventListener("blur", onLeave);
    }
    svg.append(g);
  });
  return svg;
}

// Short two-line category label per method.
const SHORT = {
  download: ["Download", "NetCDF"],
  fuse: ["FUSE", "Mountpoint"],
  table_hilbert: ["Iceberg", "DuckDB"],
  virtual: ["Virtual", "Icechunk"],
  native_ts: ["Native ts", "Icechunk"],
  native_dl: ["Native dl", "Icechunk"],
};
const cat = (id, zeroLabel) => ({ id, label: SHORT[id][0], sub: SHORT[id][1], zeroLabel });

// Direction hint shown in every legend row; every chart here plots a cost or a duration.
const better = () => h("span", { class: "wx-better" }, "↓ Lower is better");

// Table view toggle: returns {button, container, render(tableEl)}.
function tableView(card) {
  const wrap = h("div", { class: "wx-table-wrap", hidden: "" });
  const btn = h("button", { type: "button", class: "wx-act", "aria-expanded": "false" }, "Show table");
  btn.addEventListener("click", () => {
    const open = wrap.hidden;
    wrap.hidden = !open;
    btn.textContent = open ? "Hide table" : "Show table";
    btn.setAttribute("aria-expanded", String(open));
  });
  return { btn, wrap };
}
function table(headers, rows) {
  return h(
    "table",
    { class: "wx-table" },
    h("thead", {}, h("tr", {}, ...headers.map((t) => h("th", {}, t)))),
    h("tbody", {}, ...rows.map((r) => h("tr", {}, ...r.map((v) => h("td", {}, v)))))
  );
}

// Base element: card shell, resize handling, persisted state.
class WxBase extends HTMLElement {
  connectedCallback() {
    injectCss();
    this.classList.add("wx");
    this.card = h("div", { class: "wx-card" });
    this.replaceChildren(this.card);
    this.tip = tooltip(this.card);
    this.build();
    this.render();
    this._ro = new ResizeObserver(() => {
      const w = this.plot.clientWidth;
      if (Math.abs(w - (this._w || 0)) > 8) {
        this._w = w;
        this.render();
      }
    });
    this._ro.observe(this.plot);
  }
  disconnectedCallback() {
    this._ro?.disconnect();
  }
  width() {
    return this.plot.clientWidth || 720;
  }
  foot(left, right) {
    return h("div", { class: "wx-foot" }, h("p", {}, left), right);
  }
}

// ---------- 1. Storage ----------
class WxStorage extends WxBase {
  build() {
    const key = "wxtco.storage";
    this.state = Object.assign({ unit: "gb", copy: false }, storage(key, {}));
    const save = () => persist(key, this.state);
    this.plot = h("div", { class: "wx-plot" });
    this.legend = h("div", { class: "wx-legend" });
    const tv = tableView(this.card);
    this.tableWrap = tv.wrap;
    this.card.append(
      h("div", { class: "wx-head" }, h("h3", { class: "wx-title" }, "Storage"), h("p", { class: "wx-sub" }, `28 cycles of MOGREPS-G surface data, S3 Standard at $${P.s3_gb_month}/GB-month`)),
      h(
        "div",
        { class: "wx-controls" },
        h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "Unit"), segmented([{ id: "gb", label: "Bytes stored" }, { id: "usd", label: "$ per month" }], this.state.unit, (v) => { this.state.unit = v; save(); this.render(); }, "Unit")),
        h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "NetCDF copy"), segmented([{ id: "off", label: "Method's own bytes" }, { id: "on", label: "Plus original NetCDF files" }], this.state.copy ? "on" : "off", (v) => { this.state.copy = v === "on"; save(); this.render(); }, "Include the NetCDF copy"))
      ),
      this.legend,
      this.plot,
      this.foot("Download and FUSE store nothing of their own; they read the NetCDF copy. Virtual Icechunk stores 19 GB of references and needs the copy too.", tv.btn),
      tv.wrap
    );
  }
  render() {
    const { unit, copy } = this.state;
    const f = unit === "usd" ? (v) => usd(v) : gb;
    const scale = unit === "usd" ? P.s3_gb_month : 1;
    const own = { label: "Method's own bytes", color: "var(--wx-c1)", values: {} };
    const cp = { label: "NetCDF copy", color: "var(--wx-copy)", values: {} };
    for (const m of METHODS) {
      own.values[m.id] = m.storage_gb * scale;
      cp.values[m.id] = copy ? DATA.netcdf_gb * scale : 0;
    }
    const series = copy ? [own, cp] : [own];
    this.legend.replaceChildren(...(copy ? series.map((s) => h("span", {}, h("i", { style: `background:${s.color}` }), s.label)) : []), better());
    const svg = columnChart({
      cats: ORDER.map((id) => cat(id, copy ? null : "reads copy")),
      series,
      unit: unit === "usd" ? "usd" : "gb",
      fmt: f,
      width: this.width(),
      onHover: (ev, c, total, el) => {
        const m = BY_ID[c.id];
        const build = (t) => {
          t.append(h("b", {}, m.label), h("div", { class: "wx-muted" }, m.detail));
          t.append(tipRow("Own bytes", `${gb(m.storage_gb)} · ${usd(m.storage_gb * P.s3_gb_month)}/mo`, "var(--wx-c1)"));
          if (copy) t.append(tipRow("NetCDF copy", `${gb(DATA.netcdf_gb)} · ${usd(DATA.netcdf_gb * P.s3_gb_month)}/mo`, "var(--wx-copy)"));
          if (m.storage_gb > 0) t.append(h("div", { class: "wx-muted" }, `${(m.storage_gb / DATA.netcdf_gb * 100).toFixed(0)}% of the NetCDF size`));
        };
        ev ? this.tip.show(ev, build) : this.tip.showAt(el, build);
      },
      onLeave: () => this.tip.hide(),
    });
    this.plot.replaceChildren(svg);
    this.tableWrap.replaceChildren(
      table(
        ["Method", "Own bytes", "Own $/mo", "With copy", "With copy $/mo"],
        METHODS.map((m) => [m.label, gb(m.storage_gb), usd(m.storage_gb * P.s3_gb_month), gb(m.storage_gb + DATA.netcdf_gb), usd((m.storage_gb + DATA.netcdf_gb) * P.s3_gb_month)])
      )
    );
  }
}

// ---------- 2. Ingest ----------
const INGEST_IDS = ["download", "table_hilbert", "virtual", "native_ts", "native_dl"];
class WxIngest extends WxBase {
  build() {
    const key = "wxtco.ingest";
    const st = storage(key, {});
    this.state = { unit: st.unit || "min", sel: new Set(Array.isArray(st.sel) && st.sel.length ? st.sel.filter((i) => INGEST_IDS.includes(i)) : INGEST_IDS) };
    const save = () => persist(key, { unit: this.state.unit, sel: [...this.state.sel] });
    this.plot = h("div", { class: "wx-plot" });
    const tv = tableView(this.card);
    this.tableWrap = tv.wrap;
    this.unitCtl = segmented([{ id: "min", label: "Minutes per cycle" }, { id: "usd", label: "$ per cycle" }, { id: "usdmo", label: `$ per month` }], this.state.unit, (v) => { this.state.unit = v; save(); this.render(); }, "Unit");
    this.card.append(
      h("div", { class: "wx-head" }, h("h3", { class: "wx-title" }, "Ingestion"), h("p", { class: "wx-sub" }, `one forecast cycle (11,521 files, 232 GB) on a ${P.etl_instance} at $${P.etl_usd_per_hour}/h`)),
      h("div", { class: "wx-controls" }, chips(INGEST_IDS, this.state.sel, () => { save(); this.render(); }), h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "Unit"), this.unitCtl)),
      h("div", { class: "wx-legend" }, better()),
      this.plot,
      this.foot(`Download and FUSE have no ingest step. Monthly cost assumes ${DATA.workload.etl_cycles} cycles per day.`, tv.btn),
      tv.wrap
    );
  }
  render() {
    const { unit, sel } = this.state;
    const ids = INGEST_IDS.filter((i) => sel.has(i));
    if (!ids.length) {
      this.plot.replaceChildren(h("div", { class: "wx-empty" }, "Pick at least one method."));
      return;
    }
    const val = (m) => (unit === "min" ? (m.etl_seconds || 0) / 60 : unit === "usd" ? etlUsdPerCycle(m) : etlUsdPerCycle(m) * DATA.workload.etl_cycles * DAYS);
    const f = unit === "min" ? (v) => (v === 0 ? "0" : mins(v * 60)) : (v) => usd(v);
    const series = [{ label: "Ingest", color: "var(--wx-c2)", values: Object.fromEntries(ids.map((i) => [i, val(BY_ID[i])])) }];
    const svg = columnChart({
      cats: ids.map((id) => (id === "download" ? { id, label: "Download", sub: "or FUSE", zeroLabel: "no ingest" } : cat(id))),
      series,
      unit: unit === "min" ? "min" : "usd",
      fmt: f,
      width: this.width(),
      onHover: (ev, c, total, el) => {
        const m = BY_ID[c.id];
        const build = (t) => {
          t.append(h("b", {}, c.id === "download" ? "Download or FUSE" : m.label), h("div", { class: "wx-muted" }, c.id === "download" ? "queries read the NetCDF files as they are" : m.detail));
          if (m.etl_seconds == null) return t.append(h("div", {}, "No ingest step"));
          t.append(tipRow("Per cycle", `${mins(m.etl_seconds)} · ${usd(etlUsdPerCycle(m))}`));
          t.append(tipRow(`${DATA.workload.etl_cycles} cycles/day`, `${usd(etlUsdPerCycle(m) * DATA.workload.etl_cycles * DAYS)}/mo`));
          t.append(h("div", { class: "wx-muted" }, `median of ${m.etl_cycles_measured} clean cycle${m.etl_cycles_measured === 1 ? "" : "s"}`));
        };
        ev ? this.tip.show(ev, build) : this.tip.showAt(el, build);
      },
      onLeave: () => this.tip.hide(),
    });
    this.plot.replaceChildren(svg);
    this.tableWrap.replaceChildren(
      table(
        ["Method", "Seconds per cycle", "Minutes", "$ per cycle", `$ per month (${DATA.workload.etl_cycles}/day)`],
        METHODS.filter((m) => m.id !== "fuse").map((m) => [m.id === "download" ? "Download or FUSE" : m.label, m.etl_seconds == null ? "no ingest" : fmtInt(m.etl_seconds), m.etl_seconds == null ? "–" : mins(m.etl_seconds), usd(etlUsdPerCycle(m)), usd(etlUsdPerCycle(m) * DATA.workload.etl_cycles * DAYS)])
      )
    );
  }
}

// ---------- 3. Queries ----------
const PRESETS = [
  { label: "Icechunk only", ids: ["virtual", "native_ts", "native_dl"] },
  { label: "All but FUSE", ids: ORDER.filter((i) => i !== "fuse") },
  { label: "All six", ids: ORDER },
];
class WxQueries extends WxBase {
  build() {
    const key = "wxtco.queries";
    const st = storage(key, {});
    this.state = { unit: st.unit || "s", sel: new Set(Array.isArray(st.sel) && st.sel.length ? st.sel.filter((i) => ORDER.includes(i)) : PRESETS[1].ids) };
    const save = () => persist(key, { unit: this.state.unit, sel: [...this.state.sel] });
    this.plot = h("div", { class: "wx-plot wx-small" });
    const tv = tableView(this.card);
    this.tableWrap = tv.wrap;
    this.card.append(
      h("div", { class: "wx-head" }, h("h3", { class: "wx-title" }, "Query performance"), h("p", { class: "wx-sub" }, `median seconds on one ${P.query_instance}, every read from S3`)),
      h(
        "div",
        { class: "wx-controls" },
        chips(ORDER, this.state.sel, () => { save(); this.render(); }, PRESETS),
        h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "Unit"), segmented([{ id: "s", label: "Seconds" }, { id: "usd", label: "$ per 1,000 queries" }], this.state.unit, (v) => { this.state.unit = v; save(); this.render(); }, "Unit"))
      ),
      h("div", { class: "wx-legend" }, better()),
      this.plot,
      this.foot(`Each chart rescales to the slowest method picked. Cost is instance time at $${P.query_usd_per_hour}/h plus S3 requests at list price, from request counts measured with CloudWatch.`, tv.btn),
      tv.wrap
    );
  }
  render() {
    const { unit, sel } = this.state;
    const ids = ORDER.filter((i) => sel.has(i));
    this.plot.replaceChildren();
    if (!ids.length) {
      this.plot.append(h("div", { class: "wx-empty" }, "Pick at least one method."));
      return;
    }
    const val = (m, q) => (unit === "s" ? m.queries[q].seconds : queryUsd(m.queries[q]) * 1000);
    const f = unit === "s" ? secs : (v) => usd(v);
    const w = this.width();
    for (const q of ["q1", "q2", "q3"]) {
      const meta = DATA.queries[q];
      const wrap = h("div", { class: "wx-qchart" }, h("h4", {}, meta.label, h("span", {}, meta.sub)));
      const fastest = Math.min(...ids.map((i) => BY_ID[i].queries[q].seconds));
      const svg = columnChart({
        cats: ids.map((id) => cat(id)),
        series: [{ label: meta.label, color: "var(--wx-c1)", values: Object.fromEntries(ids.map((i) => [i, val(BY_ID[i], q)])) }],
        unit: unit === "s" ? "s" : "usd",
        fmt: f,
        width: w,
        heightPx: 220,
        onHover: (ev, c, total, el) => {
          const m = BY_ID[c.id], r = m.queries[q];
          const build = (t) => {
            t.append(h("b", {}, m.label), h("div", { class: "wx-muted" }, meta.label));
            t.append(tipRow("Median", secs(r.seconds)));
            if (r.wire_bytes) t.append(tipRow("Bytes moved", bytes(r.wire_bytes)));
            if (r.requests) t.append(tipRow("S3 requests", `${fmtInt(r.requests.get + r.requests.head)} GET${r.requests.list >= 1 ? ` + ${fmtInt(r.requests.list)} LIST` : ""}`));
            t.append(tipRow("Per 1,000 queries", `${usd(queryUsd(r) * 1000)} (${usd(computeUsd(r.seconds) * 1000)} compute + ${usd(requestUsd(r.requests) * 1000)} requests)`));
            const ratio = r.seconds / fastest;
            t.append(h("div", { class: "wx-muted" }, ratio < 1.005 ? "fastest selected" : `${ratio >= 10 ? ratio.toFixed(0) : ratio.toFixed(1)}x the fastest selected · ${r.runs} run${r.runs === 1 ? "" : "s"}`));
          };
          ev ? this.tip.show(ev, build) : this.tip.showAt(el, build);
        },
        onLeave: () => this.tip.hide(),
      });
      wrap.append(svg);
      this.plot.append(wrap);
    }
    this.tableWrap.replaceChildren(
      table(
        ["Method", "Q1 s", "Q1 bytes", "Q1 requests", "Q2 s", "Q2 bytes", "Q3 s (16 samples)", "Q3 bytes", "$ per 1,000 Q1"],
        METHODS.map((m) => [m.label, secs(m.queries.q1.seconds), bytes(m.queries.q1.wire_bytes), m.queries.q1.requests ? fmtInt(m.queries.q1.requests.get + m.queries.q1.requests.head) : "–", secs(m.queries.q2.seconds), bytes(m.queries.q2.wire_bytes), secs(m.queries.q3.seconds), bytes(m.queries.q3.wire_bytes), usd(queryUsd(m.queries.q1) * 1000)])
      )
    );
  }
}

// ---------- 4. TCO ----------
const PARAMS = [
  { id: "q1", label: "Q1 point series per day", min: 0, max: 100000, step: 500 },
  { id: "q2", label: "Q2 regional stats per day", min: 0, max: 100, step: 1 },
  { id: "q3", label: "Q3 training epochs per day", min: 0, max: 24, step: 1 },
  { id: "etl_cycles", label: "Forecast cycles ingested per day", min: 0, max: 8, step: 1 },
];
class WxTco extends WxBase {
  build() {
    const key = "wxtco.tco";
    const st = storage(key, {});
    this.state = {
      w: Object.assign({}, DATA.workload, st.w || {}),
      copy: st.copy ?? true,
      sel: new Set(Array.isArray(st.sel) && st.sel.length ? st.sel.filter((i) => ORDER.includes(i)) : PRESETS[1].ids),
    };
    const save = () => persist(key, { w: this.state.w, copy: this.state.copy, sel: [...this.state.sel] });
    this.plot = h("div", { class: "wx-plot" });
    const tv = tableView(this.card);
    this.tableWrap = tv.wrap;
    this.outputs = {};
    this.inputs = {};
    const params = h(
      "div",
      { class: "wx-params" },
      ...PARAMS.map((p) => {
        const out = h("output", { for: `wx-${p.id}` }, fmtInt(this.state.w[p.id]));
        const inp = h("input", { type: "range", id: `wx-${p.id}`, min: p.min, max: p.max, step: p.step, value: this.state.w[p.id] });
        inp.addEventListener("input", () => {
          this.state.w[p.id] = Number(inp.value);
          out.textContent = fmtInt(this.state.w[p.id]);
          save();
          this.render();
        });
        this.outputs[p.id] = out;
        this.inputs[p.id] = inp;
        return h("div", { class: "wx-param" }, h("label", { for: `wx-${p.id}` }, p.label, out), inp, h("small", {}, `study default ${fmtInt(DATA.workload[p.id])}`));
      })
    );
    const setW = (w) => {
      Object.assign(this.state.w, w);
      for (const p of PARAMS) {
        this.inputs[p.id].value = Math.min(p.max, this.state.w[p.id]);
        this.outputs[p.id].textContent = fmtInt(this.state.w[p.id]);
      }
      save();
      this.render();
    };
    const mult = (k) => setW({ q1: DATA.workload.q1 * k, q2: DATA.workload.q2 * k, q3: DATA.workload.q3 * k, etl_cycles: DATA.workload.etl_cycles });
    this.legend = h("div", { class: "wx-legend" }, ...COMPONENTS.map((c) => h("span", {}, h("i", { style: `background:${c.color}` }), c.label)), better());
    this.card.append(
      h("div", { class: "wx-head" }, h("h3", { class: "wx-title" }, "Monthly cost of ownership"), h("p", { class: "wx-sub" }, "storage, ingest, and query compute plus S3 requests, at us-east-1 list prices")),
      params,
      h(
        "div",
        { class: "wx-controls" },
        h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "Workload"), h("button", { type: "button", class: "wx-act", onclick: () => mult(1) }, "Study default"), h("button", { type: "button", class: "wx-act", onclick: () => mult(3) }, "3x queries"), h("button", { type: "button", class: "wx-act", onclick: () => mult(10) }, "10x queries")),
        h("div", { class: "wx-group" }, h("span", { class: "wx-label" }, "NetCDF copy"), segmented([{ id: "on", label: "Kept" }, { id: "off", label: "Deleted after ingest" }], this.state.copy ? "on" : "off", (v) => { this.state.copy = v === "on"; save(); this.render(); }, "Include the NetCDF copy in storage")),
        chips(ORDER, this.state.sel, () => { save(); this.render(); }, PRESETS)
      ),
      this.legend,
      this.plot,
      this.foot(`Compute is priced as instance-seconds (${P.etl_instance} for ingest, ${P.query_instance} for queries), serialized, with no idle time. Each query's cost includes S3 requests at list price.`, tv.btn),
      tv.wrap
    );
  }
  render() {
    const { w, copy, sel } = this.state;
    const ids = ORDER.filter((i) => sel.has(i));
    if (!ids.length) {
      this.plot.replaceChildren(h("div", { class: "wx-empty" }, "Pick at least one method."));
      return;
    }
    const all = Object.fromEntries(ORDER.map((i) => [i, costs(BY_ID[i], w, copy)]));
    const series = COMPONENTS.map((c) => ({ label: c.label, color: c.color, values: Object.fromEntries(ids.map((i) => [i, all[i][c.id]])) }));
    const svg = columnChart({
      cats: ids.map((id) => cat(id)),
      series,
      unit: "usd",
      fmt: (v) => usd(v, { compact: true }),
      width: this.width(),
      heightPx: 300,
      onHover: (ev, c, total, el) => {
        const m = BY_ID[c.id], k = all[c.id];
        const build = (t) => {
          t.append(h("b", {}, m.label), h("div", { class: "wx-muted" }, `${usd(k.total)} per month`));
          for (const comp of COMPONENTS) t.append(tipRow(comp.label, usd(k[comp.id]), comp.color));
          const req = k.requests.q1 + k.requests.q2 + k.requests.q3;
          t.append(h("div", { class: "wx-muted" }, `of which S3 requests: ${usd(req)}`));
        };
        ev ? this.tip.show(ev, build) : this.tip.showAt(el, build);
      },
      onLeave: () => this.tip.hide(),
    });
    this.plot.replaceChildren(svg);
    this.tableWrap.replaceChildren(
      table(
        ["Method", ...COMPONENTS.map((c) => c.label), "of which S3 requests", "Total per month"],
        ORDER.map((i) => [BY_ID[i].label, ...COMPONENTS.map((c) => usd(all[i][c.id])), usd(all[i].requests.q1 + all[i].requests.q2 + all[i].requests.q3), usd(all[i].total)])
      )
    );
  }
}

if (typeof customElements !== "undefined") {
  customElements.get("wxtco-storage") || customElements.define("wxtco-storage", WxStorage);
  customElements.get("wxtco-ingest") || customElements.define("wxtco-ingest", WxIngest);
  customElements.get("wxtco-queries") || customElements.define("wxtco-queries", WxQueries);
  customElements.get("wxtco-tco") || customElements.define("wxtco-tco", WxTco);
}

export { costs, DATA };
