// Generated by scripts/export_web_data.py from docs/findings. Do not edit.
export default {
  "generated": "2026-09-30",
  "commit": "a0519b1",
  "prices": {
    "s3_gb_month": 0.023,
    "s3_get_per_1000": 0.0004,
    "s3_list_per_1000": 0.005,
    "etl_instance": "c7i.16xlarge",
    "etl_usd_per_hour": 2.856,
    "query_instance": "m7i.4xlarge",
    "query_usd_per_hour": 0.8064
  },
  "workload": {
    "q1": 10000,
    "q2": 4,
    "q3": 1,
    "etl_cycles": 4
  },
  "netcdf_gb": 6494.0,
  "queries": {
    "q1": {
      "label": "Q1 point series",
      "sub": "one variable, one grid cell, 171 leads x 18 members"
    },
    "q2": {
      "label": "Q2 regional stats",
      "sub": "two variables over the UK, two cycles, CRPS"
    },
    "q3": {
      "label": "Q3 dataloader",
      "sub": "16 samples, 4 variables, full grid, batches of 8"
    }
  },
  "methods": [
    {
      "id": "download",
      "label": "Download NetCDF",
      "short": "Download",
      "detail": "whole files per query, obstore",
      "family": "file",
      "storage_gb": 0.0,
      "etl_seconds": null,
      "etl_cycles_measured": 0,
      "queries": {
        "q1": {
          "seconds": 11.8886,
          "runs": 5,
          "wire_bytes": 6108199040.0,
          "requests": {
            "get": 169.4,
            "head": 0.1,
            "list": 12.0
          }
        },
        "q2": {
          "seconds": 59.9594,
          "runs": 3,
          "wire_bytes": 22796534703.0,
          "requests": {
            "get": 613.3,
            "head": 2.0,
            "list": 23.0
          }
        },
        "q3": {
          "seconds": 38.301100000000005,
          "runs": 2,
          "wire_bytes": 2326885404.5,
          "requests": {
            "get": 57.5,
            "head": 8.2,
            "list": 25.0
          }
        }
      }
    },
    {
      "id": "fuse",
      "label": "FUSE mount",
      "short": "FUSE",
      "detail": "NetCDF read in place through Mountpoint",
      "family": "file",
      "storage_gb": 0.0,
      "etl_seconds": null,
      "etl_cycles_measured": 0,
      "queries": {
        "q1": {
          "seconds": 267.5323,
          "runs": 1,
          "wire_bytes": 8461651683.0,
          "requests": {
            "get": 16650.0,
            "head": 187.0,
            "list": 189.0
          }
        },
        "q2": {
          "seconds": 1250.4771,
          "runs": 1,
          "wire_bytes": 39073315603.0,
          "requests": {
            "get": 20505.0,
            "head": 581.0,
            "list": 585.0
          }
        },
        "q3": {
          "seconds": 248.6793,
          "runs": 1,
          "wire_bytes": 10260464808.5,
          "requests": {
            "get": 3500.0,
            "head": 82.8,
            "list": 86.5
          }
        }
      }
    },
    {
      "id": "table_hilbert",
      "label": "Iceberg",
      "short": "Iceberg",
      "detail": "Parquet, Hilbert row order, DuckDB",
      "family": "table",
      "storage_gb": 5122.4,
      "etl_seconds": 1679.0,
      "etl_cycles_measured": 2,
      "queries": {
        "q1": {
          "seconds": 27.5985,
          "runs": 5,
          "wire_bytes": 314597773.0,
          "requests": {
            "get": 5553.8,
            "head": 3.6,
            "list": 0.0
          }
        },
        "q2": {
          "seconds": 694.49,
          "runs": 3,
          "wire_bytes": 1456378359.0,
          "requests": {
            "get": 19839.9,
            "head": 19.2,
            "list": 1.6
          }
        },
        "q3": {
          "seconds": 184.063,
          "runs": 2,
          "wire_bytes": 2358745976.75,
          "requests": {
            "get": 22630.7,
            "head": 4.3,
            "list": 0.5
          }
        }
      }
    },
    {
      "id": "virtual",
      "label": "Virtual Icechunk",
      "short": "Virtual",
      "detail": "references into the NetCDF files",
      "family": "tensor",
      "storage_gb": 18.6,
      "etl_seconds": 384.0,
      "etl_cycles_measured": 28,
      "queries": {
        "q1": {
          "seconds": 0.992,
          "runs": 5,
          "wire_bytes": 82810478.0,
          "requests": {
            "get": 2477.8,
            "head": 1.4,
            "list": 0.0
          }
        },
        "q2": {
          "seconds": 18.0027,
          "runs": 3,
          "wire_bytes": 1301660555.0,
          "requests": {
            "get": 49055.3,
            "head": 0.8,
            "list": 0.0
          }
        },
        "q3": {
          "seconds": 40.708375000000004,
          "runs": 2,
          "wire_bytes": 2396877122.0,
          "requests": {
            "get": 97423.0,
            "head": 5.8,
            "list": 0.5
          }
        }
      }
    },
    {
      "id": "native_ts",
      "label": "Native Icechunk, timeseries",
      "short": "Native ts",
      "detail": "chunks (18 members, 57 leads, 16 x 16)",
      "family": "tensor",
      "storage_gb": 3646.3,
      "etl_seconds": 1506.5,
      "etl_cycles_measured": 28,
      "queries": {
        "q1": {
          "seconds": 0.1087,
          "runs": 5,
          "wire_bytes": 1532979.0,
          "requests": {
            "get": 3.0,
            "head": 0.0,
            "list": 0.2
          }
        },
        "q2": {
          "seconds": 2.2959,
          "runs": 3,
          "wire_bytes": 37559962.0,
          "requests": {
            "get": 21.7,
            "head": 1.3,
            "list": 0.0
          }
        },
        "q3": {
          "seconds": 52.053399999999996,
          "runs": 2,
          "wire_bytes": 22351972730.75,
          "requests": {
            "get": 1811.0,
            "head": 1.5,
            "list": 0.5
          }
        }
      }
    },
    {
      "id": "native_dl",
      "label": "Native Icechunk, dataloader",
      "short": "Native dl",
      "detail": "one 7.2 GB shard per (cycle, lead)",
      "family": "tensor",
      "storage_gb": 3827.7,
      "etl_seconds": 1355.5,
      "etl_cycles_measured": 28,
      "queries": {
        "q1": {
          "seconds": 0.4029,
          "runs": 5,
          "wire_bytes": 211246395.0,
          "requests": {
            "get": 298.2,
            "head": 0.0,
            "list": 0.0
          }
        },
        "q2": {
          "seconds": 6.6131,
          "runs": 3,
          "wire_bytes": 1479844038.0,
          "requests": {
            "get": 1232.7,
            "head": 0.0,
            "list": 0.3
          }
        },
        "q3": {
          "seconds": 5.98825,
          "runs": 2,
          "wire_bytes": 1017141395.75,
          "requests": {
            "get": 77.0,
            "head": 0.0,
            "list": 0.0
          }
        }
      }
    }
  ]
};
